### ISSUE TITLE
Double Escaping

### ISSUE THREAD

**Issue by hcatlin** [monterail/grape-rails-cache#6]
When I try and run the example as in the documentation... it double escapes. Aka, the whole string returned by cache() is "\" all over... :(

**Comment by teamon** [comment]
Hmmm, could you prepare an example app?

**Comment by teamon** [comment]
@hcatlin ?

**Comment by hcatlin** [comment]
Sorry, been a bit overwhelmed by other things... used a different plugin. Sorry!
